# docker-compose.yml for the nginx reverse proxy
nginx-proxy:
  container_name: nginx-proxy
  image: lroguet/rpi-nginx-proxy:latest
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro